version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker-compose build
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              TAG=${CIRCLE_TAG} docker-compose build
            fi
      - run:
          name: Test examples
          command: |
            mkdir docker-cert
            cp ${DOCKER_CERT_PATH}/* docker-cert/
            for dir in $(ls -d examples/*); do
              echo "Testing $dir"
              DOCKER_HOST=${DOCKER_HOST} DOCKER_CERT_PATH=/app/docker-cert DOCKER_TLS_VERIFY=${DOCKER_TLS_VERIFY} docker-compose -f $dir/docker-compose.package.yml up --abort-on-container-exit
            done
      - deploy:
          name: Push Docker image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker-compose push
            fi
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              TAG=${CIRCLE_TAG} docker-compose push
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DOCKER_HUB
          filters:
            tags:
              only: /.*/
