version: 2
jobs:
  build:
    docker:
      - image: docker:18.03.0-ce-git
    steps:
      - checkout
      - run:
          name: Install Docker Compose
          command: |
            wget -P ~ https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            mv ~/docker-compose /usr/local/bin/docker-compose
            docker-compose version
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker-compose build
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              TAG=${CIRCLE_TAG} docker-compose build
            fi
      - run:
          name: Test examples
          command: |
            docker-compose -f examples/multiple_images/docker-compose.package.yml up --abort-on-container-exit
            docker-compose -f examples/single_image/docker-compose.package.yml up --abort-on-container-exit
      - deploy:
          name: Push Docker image to Docker Hub
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker-compose push
            fi
            if [[ ! -z "${CIRCLE_TAG}" ]]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              TAG=${CIRCLE_TAG} docker-compose push
            fi

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: DOCKER_HUB
          filters:
            tags:
              only: /.*/
