version: '2.1'

services:
  package:
    image: bjornmagnusson/kube-app-packager
    volumes:
      - ./:/app
    environment:
      DOCKER_IMAGES: "mariadb:10.1.31"
      HELM_CHART_REPOSITORY: stable
      HELM_CHART_NAME: mariadb
      HELM_CHART_VERSION: 2.1.17
      APP_VERSION: 0.0.1-SNAPSHOT
      APP_NAME: "mariadb"
      DOCKER_HOST: ${DOCKER_HOST:-tcp://docker:2375}
      DOCKER_TLS_VERIFY: ${DOCKER_TLS_VERIFY:-}
      DOCKER_CERT_PATH: ${DOCKER_CERT_PATH:-}
    depends_on:
      - docker
  docker:
    image: docker:18.03-dind
    privileged: true
