version: '2.1'

services:
  package:
    image: bjornmagnusson/kube-app-packager
    volumes:
      - ./:/app
    environment:
      DOCKER_IMAGES: "mariadb:10.1.31"
      HELM_CHART_REPOSITORY: stable
      HELM_CHART_NAME: mariadb
      HELM_CHART_VERSION: 2.1.17
      SCRIPTS: "script1.sh,scripts"
      APP_VERSION: 2.1.17
      APP_NAME: "mariadb"
      DOCKER_HOST: tcp://docker:2375
    depends_on:
      - docker
  docker:
    image: docker:18.03-dind
    privileged: true
